UN2008 <- read.delim(file='UN2008.txt', comment.char='#')
# change the column names from the ones generated by R (X2000.2005) to the original ones (2000-2005)
get.newTFRcolnames <- function() {
	ncols <- ncol(UN2008)
	colnames.years <- colnames(UN2008)[4:ncols]
	colnames(UN2008)[4:ncols] <- substr(colnames.years, 2, 10)
	substr(colnames(UN2008)[4:ncols], 5,5) <- '-'
	return(colnames(UN2008))
}
colnames(UN2008) <- get.newTFRcolnames()
